spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_hw
    username: ${DB_USERNAME:change-me}
    password: ${DB_PASSWORD:change-me}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    org.example.spring_hw: DEBUG