CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    due_date DATE,
    priority VARCHAR(32) NOT NULL,
    tags TEXT
);

CREATE TABLE task_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    stored_file_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(255),
    size BIGINT NOT NULL,
    uploaded_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_task_attachments_task
      FOREIGN KEY (task_id)
      REFERENCES tasks (id)
      ON DELETE CASCADE
);

CREATE INDEX idx_task_attachments_task_id ON task_attachments (task_id);

